merchants = {
    "d3bc94e8-16ca-4d2e-a711-0ee3e1e42856": {
        "id": "d3bc94e8-16ca-4d2e-a711-0ee3e1e42856",
        "name": "Mama of Africa",
        "address": {
            "street": "Hauptstraße",
            "number": 10,
            "postalCode": "35390",
            "city": "Gießen"
        },
        "hours": {
            "0": [11,24],
            "1": [11,24],
            "2": [11,24],
            "3": [11,24],
            "4": [11,1],
            "5": [11,1],
            "6": [11,24],
        },
        'headerSrc': 'web',
        "headerImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVkHxB_1-NMjF263IJiO4APkAToSiKHKWjug&usqp=CAU",
        "icon": "",
        'tags': [
            ("Vegan", 0xe532, 'Vegan restaurant in the style of a fastfood diner owned by animal rights activists.'),
            ("Access", 0xe03e, 'Das Restaurant ist komplett barrierefrei und nach einem Umbau stehen auch rollstuhlgerechte Toiletten zur Verfügung'),
        ],
        "description": "",
        "rating": 4.82,
        "services": [
            {
                'name': 'Buffet',
                'id': 'abcde',
                'imageSrc': 'web',
                'image': "https://images.lecker.de/herrlich-cremige-feel-good-pasta-f9187803,id=26ecd7a8,b=lecker,w=610,cg=c.jpg",
                "timeSlots": [i for i in range(11,13+1)],
                'description': 'Ein Platz an unserem Mittagsbuffet (11:00 - 13:00 Uhr)',
                'maxGroupSize': 4,
                'maxPlaces': 4,
            },
            {
                "name": "Tischreservierung",
                "id": "abcde123",
                'imageSrc': 'web',
                'image': "https://i.ytimg.com/vi/uWJ-iQ9a7C0/maxresdefault.jpg",
                "timeSlots": [i for i in range(9,19+1)],
                "description": "Ein Tisch für bis zu 12 Personen. Perfekt für Gschäftsessen oder Geburtstage",
                'maxGroupSize': 12,
                'maxPlaces': 4,
            },
            {
                "name": "Besondere Anlässe",
                "id": "abcdeabcd",
                'imageSrc': 'web',
                'image': "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/377px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg",
                "timeSlots": [9, 15],
                "description": "Buchen Sie unser Restaurant für Ihren besonderen Anlass (Hochzeit, Konfirmation, etc.)",
                'maxGroupSize': 50,
                'maxPlaces': 1,
            }
        ],
        "category": 1,
    },
    "000000-ebe2-4aa6-8572-53aa9550b5c2": {
        "name": "Pizzeria Stern",
        "address": {
            "street": "Westanlage",
            "number": 20,
            "postalCode": "35390",
            "city": "Gießen"
        },
        "hours": {
            "0": [11,22],
            "1": [11,22],
            "2": [11,22],
            "3": [11,22],
            "4": [11,22],
            "5": [11,22],
            "6": [11,22],
        },
        "id": "000000-ebe2-4aa6-8572-53aa9550b5c2",
        'headerSrc': 'web',
        "headerImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVkHxB_1-NMjF263IJiO4APkAToSiKHKWjug&usqp=CAU",
        "icon": "",
        'tags': [
            ("Vegatarisch", 0xe532, 'Wir bieten eine breite Auswahl an vegetarischen Gerichten an'),
            ("Access", 0xe03e, 'Das Restaurant ist komplett barrierefrei und nach einem Umbau stehen auch rollstuhlgerechte Toiletten zur Verfügung'),
        ],
        "description": "",
        "rating": 3.08,
        "services": [
            {
                'name': 'Mittagsangebot',
                "id": "abcde321",
                'imageSrc': 'web',
                'image': "https://images.lecker.de/herrlich-cremige-feel-good-pasta-f9187803,id=26ecd7a8,b=lecker,w=610,cg=c.jpg",
                "timeSlots": [i for i in range(12,19+1)],
                'description': '(11:00 - 13:30 Uhr) Pizzen + Salat für 9,99€!',
                'maxGroupSize': 2,
                'maxPlaces': 10,
            },
            {
                "name": "Tischreservierung",
                "id": "abcde765",
                'imageSrc': 'web',
                'image': "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/377px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg",
                "timeSlots": [i for i in range(12,21+1)],
                "description": "Ein Tisch für bis zu 6 Personen",
                'maxGroupSize': 6,
                'maxPlaces': 10,
            }
        ],
        "category": 1,
    },
        "b8082774-0000-4aa6-8572-53aa9550b5c2": {
        "name": "Zahnarzt Franke",
        "address": {
            "street": "Goethestraße",
            "number": 4,
            "postalCode": "35398",
            "city": "Gießen"
        },
        "hours": {
            "0": [8,14],
            "1": [8,14],
            "2": [8,14],
            "3": [8,16],
            "4": [8,15],
            "5": [],
            "6": [],
        },
        "id": "b8082774-0000-4aa6-8572-53aa9550b5c2",
        'headerSrc': 'web',
        "headerImage": "https://zahnarztpraxis-oral.de/wp-content/uploads/2018/06/praxis_team.jpg",
        "icon": "",
        'tags': [
            ("Access", 0xe03e, 'Unsere Praxis ist komplett barrierefrei und nach einem Umbau stehen auch rollstuhlgerechte Toiletten zur Verfügung'),
        ],
        "description": "",
        "rating": 2.45,
        "services": [
            {
                'name': 'Routinekontrolle',
                "id": "abcde11111",
                'imageSrc': 'web',
                'image': "https://www.praxis-zahnmedizin.de/wp-content/uploads/2019/06/frau-versteht-zahnarztsprache-1024x678.jpg",
                "timeSlots": [i for i in range(8,12+1)],
                'description': 'Machen Sie jetzt einen Termin bei unserem erfahrenen Ärztteam aus!',
                'maxGroupSize': 1,
                'maxPlaces': 2,
            },
            {
                "name": "Notfall",
                "id": "abcde55555",
                'imageSrc': 'web',
                'image': "https://praxis-6e0e.kxcdn.com/wp-content/uploads/2019/01/notdienst.jpg",
                "timeSlots": [i for i in range(8,12+1)],
                "description": "Für Notfälle! Bei dringenden Fällen und außerhalb der Öffnungszeiten 01238 1203981 oder 112 anrufen!",
                'maxGroupSize': 1,
                'maxPlaces': 1,
            }
        ],
        "category": 2,
    },
        "b8082774-ebe2-4aa6-0000-53aa9550b5c2": {
        "name": "The Barber Shop",
        "address": {
            "street": "Wichernweg",
            "number": 12,
            "postalCode": "35394",
            "city": "Gießen"
        },
        "hours": {
            "0": [9,14],
            "1": [9,14],
            "2": [9,14],
            "3": [9,14],
            "4": [9,14],
            "5": [9,14],
            "6": [],
        },
        "id": "b8082774-ebe2-4aa6-0000-53aa9550b5c2",
        'headerSrc': 'web',
        "headerImage": "https://media.gq-magazin.de/photos/5c9cdd481231df0d922b89ed/master/pass/barber-shops-quer.jpg",
        "icon": "",
        'tags': [],
        "description": "",
        "rating": 1.9,
        "services": [
            {
                'name': 'Rasur',
                "id": "abcde9999",
                'imageSrc': 'web',
                'image': "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa4-Xrgd5dnCTfVG-v49nopkP3Av5CsTiJRQ&usqp=CAU",
                "timeSlots": [i for i in range(9,13+1)],
                'description': 'Schnelle Rasur für 12€',
                'maxGroupSize': 12,
                'maxPlaces': 1,
            },
            {
                "name": "Styling",
                "id": "abcde9988",
                'imageSrc': 'web',
                'image': "https://bart.style/wp-content/uploads/2021/08/mann-mit-bart.png",
                "timeSlots": [i for i in range(9,13+1)],
                "description": "Einmal Rundumstyling",
                'maxGroupSize': 12,
                'maxPlaces': 1,
            }
        ],
        "category": 4,
    },
        "b8082774-ebe2-4aa6-8572-00000550b5c2": {
        "name": "Bowling Valley",
        "address": {
            "street": "Justus-Kilian-Str.",
            "number": 1,
            "postalCode": "35457",
            "city": "Lollar"
        },
        "hours": {
            "0": [11,24],
            "1": [11,24],
            "2": [11,24],
            "3": [11,24],
            "4": [11,1],
            "5": [11,1],
            "6": [11,24],
        },
        "id": "b8082774-ebe2-4aa6-8572-00000550b5c2",
        'headerSrc': 'web',
        "headerImage": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Bowlerbowling.JPG",
        "icon": "",
        'tags': [
            ("Access", 0xe03e, 'Die Bowling-Halle ist komplett barrierefrei und nach einem Umbau stehen auch rollstuhlgerechte Toiletten zur Verfügung'),
        ],
        "description": "",
        "rating": 3.7,
        "services": [
            {
                'name': 'Gruppen-Ticket',
                "id": "abcde65656",
                'imageSrc': 'web',
                'image': "https://www.hamburg.de/iason/images/6063338a2799585facb24862/s.768xb/gkgegk+pixabay.com.jpg",
                "timeSlots": [i for i in range(11,23+1)],
                'description': 'Ein Ticket für eine Stunde Bowling Bahn (bis zu 8 Personen)',
                'maxGroupSize': 8,
                'maxPlaces': 1,
            },
            {
                "name": "Cocktail-Event",
                "id": "abcde45454",
                'imageSrc': 'web',
                'image': "https://tenpineatery.com/2017website/wp-content/uploads/2019/03/Cocktails-Alley-1.jpg",
                "timeSlots": [i for i in range(20,23+1)],
                "description": "Unser Abendliches Cocktail-Event mit DJ",
                'maxGroupSize': 4,
                'maxPlaces': 5,
            }
        ],
        "category": 3,
    }
}
